# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3225d5f4d993be21ad505dc7c486d47bd4e8ccc9a2c1c7970fc1c7604048b3075991de65f7b20070b4c35feba3d87e13365ee8dea898f58a3d3b45e5da483886

test:
  secret_key_base: fb1cd8226c934d149f48a47f82ca32ce873871a7e08dca45d94d0ef9f1f0be8570ea8a04e1aa104a8d16ce6ec91a886d513330ef90463b824fcda879e1389bb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
